name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Generate lockfile if needed
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Generating package-lock.json file"
            npm install --package-lock-only
          fi
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
          
      - name: Install dependencies
        run: npm install
        
      - name: Create .solhint.json if missing
        run: |
          if [ ! -f .solhint.json ]; then
            echo "Creating .solhint.json file"
            echo '{
              "extends": "solhint:recommended",
              "rules": {
                "compiler-version": ["error", "^0.8.0"],
                "func-visibility": ["warn", {"ignoreConstructors": true}]
              }
            }' > .solhint.json
          fi
        
      - name: Install Solhint
        run: npm install -g solhint
        
      - name: Lint Solidity
        run: solhint 'AidChain.sol' -f table
        
      - name: Setup Hardhat environment
        run: |
          npm install --save-dev hardhat @nomiclabs/hardhat-waffle @nomiclabs/hardhat-ethers ethereum-waffle ethers chai
          mkdir -p contracts
          cp AidChain.sol contracts/
          
      - name: Run Backend Tests
        run: npm run test:backend
        
      - name: Show contract compilation info
        run: |
          echo "=== Contract Information ==="
          echo "Showing available contracts:"
          npx hardhat compile --show-stack-traces
          echo "=== End Contract Information ==="
          
      - name: Notify test completion
        run: echo "All tests passed! Vercel will handle the deployment automatically." 